### PR TITLE
Added protection from brute force method

### PR DESCRIPTION
**Pull request by MichalMonko**

### CODE REVIEW

**Comment by MichalMonko** [comment]
DO NOT MERGE BEFORE DEMO!

**Review by kamilturek — APPROVED** [review]
Prima sort.

**Comment by igorklepuszewski** [comment]
@kamilturek mozna mergowac?

**Review by igorklepuszewski — CHANGES_REQUESTED** [review]
screenshot from 2019-01-08 12-42-43
All floors etc. deleted

Typed wrong password 5 times and nothing really happend :-1:

**Pull request merged**
